# Generated by Django 5.0.2 on 2024-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_eeuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='eeuser',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='eeuser',
            name='language',
            field=models.CharField(choices=[('kr', 'Узбекский язык'), ('ru', 'Русский язык'), ('us', 'Английский язык'), ('in', 'Хинди'), ('vn', 'Вьетнамский'), ('tr', 'Турецкий язык')], default='ru', max_length=255, verbose_name='Язык'),
        ),
    ]
