# Generated by Django 5.0.2 on 2024-02-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_category_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ru',
        ),
    ]
