# Generated by Django 5.0.2 on 2024-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_name_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(null=True, upload_to='file/', verbose_name='Документ'),
        ),
    ]
