# Generated by Django 5.0.2 on 2024-02-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_category_name_in_category_name_tr_category_name_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('progress', 'В процессе'), ('completed', 'Выполнено')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
