# Generated by Django 5.0.2 on 2024-02-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='creator',
        ),
    ]
