# Generated by Django 5.0.2 on 2024-02-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_rename_user_application_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('created', 'Направлено на исполнение'), ('progress', 'В процессе'), ('completed', 'Выполнено')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
