# Generated by Django 5.0.2 on 2024-02-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Документ'),
        ),
    ]
